### ISSUE TITLE
Reference genomes on Babraham Bioinformatics website are no longer available for download

### ISSUE THREAD

**Issue by kuanyili** [StevenWingett/FastQ-Screen#69]
Running

```shell
fastq_screen --get_genomes
```

as instructed [here](https://stevenwingett.github.io/FastQ-Screen/#obtaining-reference-genomes) will return a `404 NOT FOUND` against https://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes/

**Comment by StevenWingett** [comment]
Hi,

Thank you for bringing this to my attention.  I've just found out that that the genome server was discontinued.  We are now moving the genomes to a new location and this functionality should start working shortly.  I'll let you know when it is working.

Best,
Steven

**Comment by StevenWingett** [comment]
Hi,

This should now be working.  Please let me know if you have any problems downloading the genomes via FastQ Screen.

Best,
Steven

**Comment by chrismitbiz** [comment]
Hi there, 
I still have issues connecting to the (new) server with the --get_genomes command. See here:


![Screenshot 2024-04-17 at 9 49 04 AM](https://github.com/StevenWingett/FastQ-Screen/assets/41090830/486c9aca-7c45-4d5f-8023-5faa89f243fc)

Best, 
Chris

**Comment by StevenWingett** [comment]
It has been brought to my attention that some users are still having problems downloading the genomes.  This seems to be a result of the old server location being saved on their machines.  To solve this issue, delete the file genome_locations.txt you downloaded from before and then try again.

Steven
